### ISSUE TITLE
Rythm ClassLoader does not have access to things

### ISSUE THREAD

**Issue by jkcclemens** [Chatterbox/Chatterbox#28]
Very vague title, yo. Writing the Factions hook, I discovered that Rythm's classloader does not have access to Factions classes, although they are loaded. I thought I had fixed my classloader woes, but I must dive back into that hideous world.

**Comment by jkcclemens** [comment]
See [this issue](https://github.com/greenlaw110/Rythm/issues/272) on Rythm's repo. This is an issue with Rythm, not Chatterbox.

**Comment by greenlaw110** [comment]
Interesting, would like to understand how the Factions class is loaded? Can you find out the classloader of the Factions class at runtime?

**Comment by jkcclemens** [comment]
It should be a PluginClassLoader, but I'll double-check.

**Comment by greenlaw110** [comment]
Okay, so is that `PluginClassLoader` the same thing with `chatterbox.getClass().getClassLoader()`?

**Comment by jkcclemens** [comment]
Yes. If you use ```chatterbox.getClass.getClassLoader().findClass(<name here>)```, you get the class.

**Comment by jkcclemens** [comment]
I just set a breakpoint and was able to execute two sections of code.
```((ClassLoader) ((TagStage)this).chatterbox.getAPI().getRythmAPI().rythm._classLoader).parent.findClass("com.massivecraft.factions.zcore.persist.json.JSONFaction")```, which is just getting the parent classloader of RythmEngine's classloader, finds the class.

```((TagStage)this).chatterbox.getAPI().getRythmAPI().rythm._classLoader.findClass("com.massivecraft.factions.zcore.persist.json.JSONFaction")``` throws a ClassNotFoundException.

I can confirm that the exception is coming from not implementing findClass(String). Stack trace is proving this.

**Comment by greenlaw110** [comment]
`ClassLoader.findClass()` is invoked by `ClassLoader.loadClass(String, boolean)`, and Rythm's `TemplateClassLoader` shall not invoke that `findClass()` method, instead it shall always delegate to parent class loader for classes other than a Template class. Would you be able to break at Rythm's `classloader.findClass()` and check where the call is coming from?

**Comment by jkcclemens** [comment]
Perhaps. The shading will make it difficult, but I may be able to get around it.

**Comment by jkcclemens** [comment]
Okay, well, this is interesting. I may be wrong about findClass.
```
"Async Chat Thread - #4@7660" daemon prio=5 tid=0x57 nid=NA runnable
  java.lang.Thread.State: RUNNABLE
	  at works.chatterbox.chatterbox.shaded.org.rythmengine.internal.compiler.TemplateCompiler$2.acceptResult(TemplateCompiler.java:290)
	  at works.chatterbox.chatterbox.shaded.org.eclipse.jdt.internal.compiler.Compiler.handleInternalException(Compiler.java:678)
	  at works.chatterbox.chatterbox.shaded.org.eclipse.jdt.internal.compiler.Compiler.compile(Compiler.java:522)
	  at works.chatterbox.chatterbox.shaded.org.rythmengine.internal.compiler.TemplateCompiler.compile(TemplateCompiler.java:341)
	  at works.chatterbox.chatterbox.shaded.org.rythmengine.internal.compiler.TemplateClass.compile(TemplateClass.java:677)
	  - locked <0x1e13> (a works.chatterbox.chatterbox.shaded.org.rythmengine.internal.compiler.TemplateClass)
	  at works.chatterbox.chatterbox.shaded.org.rythmengine.internal.compiler.TemplateClassLoader.loadTemplateClass(TemplateClassLoader.java:308)
	  at works.chatterbox.chatterbox.shaded.org.rythmengine.internal.compiler.TemplateClassLoader.loadClass(TemplateClassLoader.java:254)
	  - locked <0x1d89> (a works.chatterbox.chatterbox.shaded.org.rythmengine.internal.compiler.TemplateClassLoader)
	  at works.chatterbox.chatterbox.shaded.org.rythmengine.internal.compiler.TemplateClass.getJavaClass(TemplateClass.java:371)
	  at works.chatterbox.chatterbox.shaded.org.rythmengine.internal.compiler.TemplateClass.templateInstance_(TemplateClass.java:387)
	  at works.chatterbox.chatterbox.shaded.org.rythmengine.internal.compiler.TemplateClass.asTemplate(TemplateClass.java:413)
	  at works.chatterbox.chatterbox.shaded.org.rythmengine.internal.compiler.TemplateClass.asTemplate(TemplateClass.java:419)
	  at works.chatterbox.chatterbox.shaded.org.rythmengine.RythmEngine.getTemplate(RythmEngine.java:924)
	  at works.chatterbox.chatterbox.shaded.org.rythmengine.RythmEngine.getTemplate(RythmEngine.java:945)
	  at works.chatterbox.chatterbox.shaded.org.rythmengine.RythmEngine.render(RythmEngine.java:1019)
	  at works.chatterbox.chatterbox.api.rythm.RythmAPI.render(RythmAPI.java:139)
	  - locked <0x1dad> (a works.chatterbox.chatterbox.shaded.org.rythmengine.RythmEngine)
	  at works.chatterbox.chatterbox.pipeline.stages.impl.rythm.RythmStage.process(RythmStage.java:70)
	  at works.chatterbox.chatterbox.pipeline.MessagePipeline.lambda$send$29(MessagePipeline.java:155)
	  at works.chatterbox.chatterbox.pipeline.MessagePipeline$$Lambda$31.1993844558.accept(Unknown Source:-1)
	  at java.util.ArrayList.forEach(ArrayList.java:1249)
	  at works.chatterbox.chatterbox.pipeline.MessagePipeline.send(MessagePipeline.java:153)
	  at works.chatterbox.chatterbox.pipeline.MessagePipeline.send(MessagePipeline.java:141)
	  at works.chatterbox.chatterbox.listeners.ChatterboxListener.onChat(ChatterboxListener.java:71)
	  at sun.reflect.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java:-1)
	  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	  at java.lang.reflect.Method.invoke(Method.java:483)
	  at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:301)
	  at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
	  at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502)
	  at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484)
	  at net.minecraft.server.v1_8_R2.PlayerConnection.chat(PlayerConnection.java:1061)
	  at net.minecraft.server.v1_8_R2.PlayerConnection.a(PlayerConnection.java:999)
	  at net.minecraft.server.v1_8_R2.PacketPlayInChat$1.run(PacketPlayInChat.java:39)
	  at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	  at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	  at java.lang.Thread.run(Thread.java:745)
```
Forgive my shading.

TemplateClassLoader is having ```loadClass``` called with ```C0ed96259_051f_3a6e_84ce_2503a832bbe6__R_T_C__194730669```, a compiled template, no doubt.

This template contains ```protected com.massivecraft.factions.zcore.persist.json.JSONFaction faction=null;```, which is causing the issue. Again, the parent ClassLoader *can* find this class.

**Comment by jkcclemens** [comment]
What's interesting is that TemplateClassLoader#loadClass and its parent's #loadClass can both find ```com.massivecraft.factions.zcore.persist.json.JSONFaction```, but only the parent #findClass can find it.

**Comment by greenlaw110** [comment]
`TemplateClassLoader` hasn't implemented the `findClass` method at all, so it will always throw out the `ClassNotFoundException`, but as I said it shall not call to that method, actually
the implementation of `TemplateClassLoader.loadClass()` method (see https://github.com/greenlaw110/Rythm/blob/master/src/main/java/org/rythmengine/internal/compiler/TemplateClassLoader.java#L224) shows there is no place to call `findClass()`, it delegate to `super.loadClass()` method in the end if the class not found, which will delegate to the `parent.loadClass()` method anyway

**Comment by jkcclemens** [comment]
Yes, I'm aware that it will always throw that. I do not see how the class isn't being found by the compiler, though. The only indication I have found that it isn't being found is because findClass isn't implemented.

It all sounds good. However, either something is calling findClass or something is flawed, because ```super.loadClass()``` and ```TemplateClassLoader.loadClass()``` both work, but the compiler doesn't find the necessary class.

**Comment by greenlaw110** [comment]
Actually can you post the full error stack of the `ClassNotFoundException` here?

**Comment by jkcclemens** [comment]
The best I really get is
```
[23:57:11 WARN]: Caused by: works.chatterbox.chatterbox.shaded.org.rythmengine.exception.CompileException: com.massivecraft.factions.zcore.persist.json.JSONFaction cannot be resolved to a type
```
I'm trying to find an actual exception thrown by jdt somewhere to post.

**Comment by greenlaw110** [comment]
Just curious, if you set the breakpoint to some where, are you able to do something like `<theTemplateClassLoader>.getResourceAsStream("/com/massivecraft/factions/zcore/persist/json/JSONFaction.class")`?

**Comment by jkcclemens** [comment]
Running that exact ```getResourceAsStream``` for both the TemplateClassLoader and its parent both return ```null```.

**Comment by greenlaw110** [comment]
What if `<theTemplateClassLoader>.getResourceAsStream("com/massivecraft/factions/zcore/persist/json/JSONFaction.class")`?

**Comment by jkcclemens** [comment]
Also ```null``` on both. Already checked.

**Comment by greenlaw110** [comment]
That's strange. It should anyway be able to get the class file as a resource stream. How did that `PluginClassLoader` load class bytecode?

**Comment by jkcclemens** [comment]
See [here](https://hub.spigotmc.org/stash/projects/SPIGOT/repos/bukkit/browse/src/main/java/org/bukkit/plugin/java/PluginClassLoader.java). Still looking for the root exception in jdt.

**Comment by greenlaw110** [comment]
I think you need to override `URL ClassLoader.findResource(String)` method in your `PluginClassLoader` class because it's using a specific `JavaPluginLoader` to load the class, and the default `findResource(String)` implementation in `URLClassLoader`, your super class won't work as expected

**Comment by jkcclemens** [comment]
I can give it a shot in a few hours.

**Comment by jkcclemens** [comment]
Alright. Busy day today. Not sure how PluginClassLoader#findResource(String) would even be overridden. There's not much I can do from there.

**Comment by jkcclemens** [comment]
Okay, after doing some breakpoint testing, I have verified that you are correct; the findResources method needs to be implemented in order to find these Factions classes.

**Comment by jkcclemens** [comment]
Thank you, @greenlaw110. This probably would have been beyond me to figure out!

**Comment by greenlaw110** [comment]
No worries @jkcclemens glad that you find your way out :-)
