### ISSUE TITLE
Non-working default setup

### ISSUE THREAD

**Issue by gdude2002** [Chatterbox/Chatterbox#38]
Using build 94 and Spigot

![](http://i.imgur.com/mVpywdq.png)

```
[14:01:32 ERROR]: Could not pass event AsyncPlayerChatEvent to Chatterbox v1.0.0-SNAPSHOT-94-78a2142
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:303) ~[spigot.jar:git-Spigot-"1ccd086"]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-"1ccd086"]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:509) [spigot.jar:git-Spigot-"1ccd086"]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:491) [spigot.jar:git-Spigot-"1ccd086"]
        at net.minecraft.server.v1_8_R1.PlayerConnection.chat(PlayerConnection.java:1004) [spigot.jar:git-Spigot-"1ccd086"]
        at net.minecraft.server.v1_8_R1.PlayerConnection.a(PlayerConnection.java:943) [spigot.jar:git-Spigot-"1ccd086"]
        at net.minecraft.server.v1_8_R1.PacketPlayInChat.a(PacketPlayInChat.java:26) [spigot.jar:git-Spigot-"1ccd086"]
        at net.minecraft.server.v1_8_R1.PacketPlayInChat$1.run(PacketPlayInChat.java:47) [spigot.jar:git-Spigot-"1ccd086"]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_45]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_45]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_45]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_45]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_45]
Caused by: java.lang.UnsupportedOperationException: SuperPerms no group permissions.
        at net.milkbowl.vault.permission.plugins.Permission_SuperPerms.getPrimaryGroup(Permission_SuperPerms.java:96) ~[?:?]
        at net.milkbowl.vault.permission.Permission.getPrimaryGroup(Permission.java:726) ~[?:?]
        at net.milkbowl.vault.permission.Permission.getPrimaryGroup(Permission.java:738) ~[?:?]
        at works.chatterbox.hooks.vault.listeners.PlayerListener.onChat(PlayerListener.java:79) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_45]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_45]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_45]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_45]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:299) ~[spigot.jar:git-Spigot-"1ccd086"]
        ... 12 more
[14:01:32 WARN]: java.lang.RuntimeException: An exception occurred while running the stage JSONStage
[14:01:32 WARN]:        at works.chatterbox.chatterbox.pipeline.MessagePipeline.lambda$send$23(MessagePipeline.java:162)
[14:01:32 WARN]:        at works.chatterbox.chatterbox.pipeline.MessagePipeline$$Lambda$45/1330681371.accept(Unknown Source)
[14:01:32 WARN]:        at java.util.ArrayList.forEach(Unknown Source)
[14:01:32 WARN]:        at works.chatterbox.chatterbox.pipeline.MessagePipeline.send(MessagePipeline.java:153)
[14:01:32 WARN]:        at works.chatterbox.chatterbox.pipeline.MessagePipeline.send(MessagePipeline.java:141)
[14:01:32 WARN]:        at works.chatterbox.chatterbox.listeners.ChatterboxListener.onChat(ChatterboxListener.java:97)
[14:01:32 WARN]:        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[14:01:32 WARN]:        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[14:01:32 WARN]:        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[14:01:32 WARN]:        at java.lang.reflect.Method.invoke(Unknown Source)
[14:01:32 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:299)
[14:01:32 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[14:01:32 WARN]:        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:509)
[14:01:32 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:491)
[14:01:32 WARN]:        at net.minecraft.server.v1_8_R1.PlayerConnection.chat(PlayerConnection.java:1004)
[14:01:32 WARN]:        at net.minecraft.server.v1_8_R1.PlayerConnection.a(PlayerConnection.java:943)
[14:01:32 WARN]:        at net.minecraft.server.v1_8_R1.PacketPlayInChat.a(PacketPlayInChat.java:26)
[14:01:32 WARN]:        at net.minecraft.server.v1_8_R1.PacketPlayInChat$1.run(PacketPlayInChat.java:47)
[14:01:32 WARN]:        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[14:01:32 WARN]:        at java.util.concurrent.FutureTask.run(Unknown Source)
[14:01:32 WARN]:        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[14:01:32 WARN]:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[14:01:32 WARN]:        at java.lang.Thread.run(Unknown Source)
[14:01:32 WARN]: Caused by: java.lang.NoClassDefFoundError: com/google/gson/JsonParser
[14:01:32 WARN]:        at works.chatterbox.chatterbox.shaded.mkremins.fanciful.FancyMessage.<clinit>(FancyMessage.java:59)
[14:01:32 WARN]:        at works.chatterbox.chatterbox.pipeline.stages.impl.json.JSONStage.handleJSON(JSONStage.java:94)
[14:01:32 WARN]:        at works.chatterbox.chatterbox.pipeline.stages.impl.json.JSONStage.single(JSONStage.java:286)
[14:01:32 WARN]:        at works.chatterbox.chatterbox.pipeline.stages.impl.json.JSONStage.process(JSONStage.java:308)
[14:01:32 WARN]:        at works.chatterbox.chatterbox.pipeline.MessagePipeline.lambda$send$23(MessagePipeline.java:160)
[14:01:32 WARN]:        ... 22 more
[14:01:32 WARN]: Caused by: java.lang.ClassNotFoundException: com.google.gson.JsonParser
[14:01:32 WARN]:        at java.net.URLClassLoader.findClass(Unknown Source)
[14:01:32 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101)
[14:01:32 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86)
[14:01:32 WARN]:        at java.lang.ClassLoader.loadClass(Unknown Source)
[14:01:32 WARN]:        at java.lang.ClassLoader.loadClass(Unknown Source)
[14:01:32 WARN]:        ... 27 more
[14:01:32 INFO]: []Start JSON display-name[]arbot[]End JSON display-name[]: test
```

**Comment by WizardCM** [comment]
Make sure you're using the latest Spigot. Early Spigot 1.8 builds don't include Gson.

**Comment by gdude2002** [comment]
@WizardCM Thanks, rebuilt it now, testing again

**Comment by gdude2002** [comment]
Okay, JSON error is gone, so we're left with this.

```
[14:11:01 ERROR]: Could not pass event AsyncPlayerChatEvent to Chatterbox v1.0.0-SNAPSHOT-94-78a2142
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot.jar:git-Spigot-ae40327-8c14eb4]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-ae40327-8c14eb4]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-ae40327-8c14eb4]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484) [spigot.jar:git-Spigot-ae40327-8c14eb4]
        at net.minecraft.server.v1_8_R3.PlayerConnection.chat(PlayerConnection.java:1057) [spigot.jar:git-Spigot-ae40327-8c14eb4]
        at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:995) [spigot.jar:git-Spigot-ae40327-8c14eb4]
        at net.minecraft.server.v1_8_R3.PacketPlayInChat$1.run(PacketPlayInChat.java:39) [spigot.jar:git-Spigot-ae40327-8c14eb4]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_45]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_45]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_45]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_45]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_45]
Caused by: java.lang.UnsupportedOperationException: SuperPerms no group permissions.
        at net.milkbowl.vault.permission.plugins.Permission_SuperPerms.getPrimaryGroup(Permission_SuperPerms.java:96) ~[?:?]
        at net.milkbowl.vault.permission.Permission.getPrimaryGroup(Permission.java:726) ~[?:?]
        at net.milkbowl.vault.permission.Permission.getPrimaryGroup(Permission.java:738) ~[?:?]
        at works.chatterbox.hooks.vault.listeners.PlayerListener.onChat(PlayerListener.java:79) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_45]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_45]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_45]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_45]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot.jar:git-Spigot-ae40327-8c14eb4]
        ... 11 more
[14:11:02 INFO]: arbot: test
```

**Comment by WizardCM** [comment]
For that, my guess is you need a SuperPerms-powered Permissoins plugin. :P

**Comment by gdude2002** [comment]
I'd assume that's what's causing the exception to be thrown, but I feel like the hook should either pick this up or catch the exception

**Comment by WizardCM** [comment]
It's a Vault issue, not a Chatterbox issue.

**Comment by gdude2002** [comment]
Regardless the hook shouldn't be causing the event to fail.

**Comment by WizardCM** [comment]
That's what I'm saying, 
> Caused by: java.lang.UnsupportedOperationException: SuperPerms no group permissions.
>         at net.milkbowl.vault.permission.plugins.Permission_SuperPerms.getPrimaryGroup(Permission_SuperPerms.java:96) ~[?:?]

Explicitly states it's caused by *Vault*, not the hook.

**Comment by gdude2002** [comment]
Yes, but "Not my problem" isn't good enough here, there's an exception being thrown that is breaking the event, by something called at `works.chatterbox.hooks.vault.listeners.PlayerListener.onChat(PlayerListener.java:79)` - this should stop the propagation by catching the exception or implementing a check.

**Comment by frymaster** [comment]
>For that, my guess is you need a SuperPerms-powered Permissoins plugin

It's actually the exact opposite

https://github.com/MilkBowl/Vault/blob/master/src/net/milkbowl/vault/permission/plugins/Permission_SuperPerms.java#L96

What that's saying is that Vault is using SuperPerms (ie normal Bukkit permissions with no explicit support for extra vault features) for its back-end permission system, which doesn't have the concept of a primary group, and so if you ask vault what the primary group is for a user, it will tell you you can't.

Ideally Chatterbox should be calling Vault's [hasGroupSupport()](http://milkbowl.github.io/VaultAPI/net/milkbowl/vault/permission/Permission.html#hasGroupSupport()) method and either coping without groups if necessary, or informing the user that they need to use a permissions plugin that supports Vault groups if that's not possible

**Comment by Ribesg** [comment]
Yup, Chatterbox expecting groups is wrong.
* Check that there is group support with what @frymaster said and fail correctly, or
* Don't require groups to be a thing at all, or
* Fallback to own implementation of the concept of groups (which should be *nothing else* than a single permission per group)

**Comment by jkcclemens** [comment]
Very helpful, @frymaster. Should be an easy fix, then! Thank you.
